### PR TITLE
change to a simpler responses

### PR DESCRIPTION
**Pull request by billbsing**
I feel that we need to make the response text simpler and cleaner.

scheduled => wait
running => run
succeeded => ok
failed => fail
cancelled => cancel
 
Change the return 'errorCode' to snake case 'error_code'

### CODE REVIEW

**Comment by mikera** [comment]
Suggested criteria for status codes:
1. Logically sound (mutually exclusive, collectively exhaustive)
2. Useful / actionable (i.e. what should caller do next?)
3. Easily understandable (clear meaning to humans)
4. Consistent grammar (e.g. all adjectives)
5. Consistent with commonly accepted standards

I prefer the current statuses on the grounds of 4

**Comment by billbsing** [comment]
I'm trying to follow more along the lines of http standards, but most of these words are not used in other protocols.

> 200 Succeeded

but a shorter more elegant solution
> 200 OK

would this be a better choice?
So I would say that the current status words do not meet #2 & especially #3

**Comment by shark8me** [comment]
The current status fields have been borrowed from other Job management
frameworks, such as Apache Spark.

I feel the status field needs to be a noun, not a verb. Http APIs are meant
to be verbs.
In this case, the verb is 'invoke', and the status fields returner in thr
response, are nouns (the status post invocation).

**Comment by mikera** [comment]
Without a strong rationale for change, I don't see any reason to change this right now. Doesn't seem to be a high priority.

If anyone can present a clear rationale for an alternative naming, happy to consider.

**Pull request closed without merging**
