### PR TITLE
Update API endpoints

### PR DESCRIPTION
**Pull request by shark8me**
Update API endpoints to 

- suggested path `/api/version/invoke`

Current APIs required are:

1. "/sync/did" : this is the synchronous invoke
2. "/async/did" : this is the async version
3. "/jobs/job-id": the API for getting job status and result

Fix for #37 & #29

### CODE REVIEW

**Comment by mikera** [comment]
I don't see why we should have separate "status" and "result" endpoints. A single map can convey all that is needed:

```json
{:jobid "134",
 :status "completed",
 :results {........}
```

This can serve as the result of an async or sync invoke, and also as the result from a `jobs/id` request. So you only have one return type to handle!

I think we should prefer plurals when addressing objects, e.g. `jobs/id`` rather than `job/id`. This appears to be the usual convention.

**Comment by shark8me** [comment]
This requirement was raised by you in a review (see https://github.com/DEX-Company/koi-clj/issues/37).

**Comment by mikera** [comment]
That's useful for Koi as an implementation (potentially), but I think we should avoid it in DEPs. The aim for the DEP Standards is to have as small an API surface as possible since it will be mandatory for all implementers.

**Comment by shark8me** [comment]
In that case, I'll also revert Koi to implement just a single API (it's already been changed).

**Comment by shark8me** [comment]
@mikera its been updated, please review

**Comment by mikera** [comment]
@shark8me feel free to merge as you are the editor for this one!

**Pull request merged**
