### PR TITLE
Add url to base asset attributes

### PR DESCRIPTION
**Pull request by billbsing**

### CODE REVIEW

**Comment by mikera** [comment]
This doesn't belong in asset metadata. The asset content might be available at many different URLs, and the canonical way to request it should be using the Storage API of DEP7

**Comment by billbsing** [comment]
But I need a way to pass the URL of the asset for squid. I also need another field 'filename' since this is also needed for PD case to keep a record of the filename linked to the asset data

**Comment by mikera** [comment]
That should presumably go in the Squid metadata, not the Asset metadata from the DEP8 perspective?

You could include arbitrary JSON data in the "additionalInformation" of course, but I still think this isn't appropriate for asset metadata for the reason above.

**Comment by billbsing** [comment]
we have
        'name',
        'type',
        'description',
        'dateCreated',
        'author',
        'license',
        'copyrightHolder',
        'links',
        'inLanguage',
        'tags',
 which are also used in the Squid metadata items

In that case maybe move the `url` & `filename` to be part of the data asset? as always non required

**Comment by mikera** [comment]
I'm reviewing these at the moment I think we can kill most of them for DEP8. Needs to be a pretty strong justification for an attribute to be defined in the standard, I think

**Pull request closed without merging**
